[package]
name = "actix-bincode"
version = "0.1.0"
edition = "2021"
authors = ["Olli Paananen <paananen.olli@tuta.io>"]
keywords = ["actix", "web", "bincode"]
repository = "https://github.com/aalhitennf/actix-bincode"
license = "MIT OR Apache-2.0"
readme = "README.md"
licence-file = "LICENSE"

[lib]
name = "actix_bincode"
path = "src/lib.rs"

[dependencies]
actix-web = "4.2.1"
bincode = "1.3.3"
derive_more = "0.99.17"
futures = "0.3.25"
serde = { version = "1.0.147", features = ["derive"] }
